<?php
/** @var  $error \BitWeb\ErrorReporting\Error */
$error = $this->error;
$meta = $error->getMeta();
?>
<html>
    <body>
        <h1>Errors occurred</h1>
        <table>
            <tr>
                <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">Link:</td>
                <td>
                    <a href="<?php echo $meta->getUrl(); ?>" target="_blank"><?php echo $meta->getUrl(); ?>
                </td>
            </tr>
            <?php if ($meta->getGetData() != null): ?>
                <tr>
                    <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">GET-data:</td>
                    <td>
                        <?php echo print_r($meta->getGetData(), true); ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($meta->getPostData() != null): ?>
                <tr>
                    <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">POST-data:</td>
                    <td>
                        <?php echo print_r($meta->getPostData(), true); ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($meta->getSessionData() != null): ?>
                <tr>
                    <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">SESSION-data:</td>
                    <td>
                        <?php echo print_r($meta->getSessionData(), true); ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if (trim($meta->getReferrer()) != ''): ?>
                <tr>
                    <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">Referrer:</td>
                    <td>
                        <a href="<?php echo $meta->getReferrer(); ?>" target="_blank"><?php echo $meta->getReferrer(); ?></a>
                    </td>
                </tr>
            <?php endif; ?>
            <tr>
                <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">User-agent:</td>
                <td>
                    <?php echo $meta->getUserAgent(); ?>
                </td>
            </tr>
            <tr>
                <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">Time of request:</td>
                <td>
                    <span>~</span>
                    <span>
                        <?php echo $meta->getRequestDuration(); ?>
                    </span>
                    <span>ms</span>
                    <span>, </span>
                    <span>
                        <?php echo $meta->getRequestTime()->format('d.m.Y H:i'); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">IP:</td>
                <td>
                    <?php echo $meta->getIp(); ?>
                </td>
            </tr>
            <tr>
                <td style="white-space:nowrap;padding-right:5px;font-weight:bold;text-align:right;">PHP:</td>
                <td>
                    <?php echo $meta->getPhpVersion(); ?>
                </td>
            </tr>
        </table>
        <table style="margin:10px;">
            <?php foreach ($error->getErrors() as $errorInfo): /** @var $errorInfo \BitWeb\ErrorReporting\ErrorInfo */ ?>
                <tr>
                    <th style="vertical-align:top;text-align:left;font-weight:bold;">
                        <?php echo $errorInfo->getTitle(); ?>
                    </th>
                </tr>
                <tr>
                    <td style="font-size:11px">
                        <?php echo $errorInfo->getClass(); ?>
                    </td>
                </tr>
                <?php if ($errorInfo->getSeverity() !== null): ?>
                    <tr>
                        <th style="vertical-align:top;text-align:left;">
                            <span>Severity</span>
                            <span style="font-weight:bold;">
                                <?php echo $errorInfo->getSeverity(); ?>
                            </span>
                        </th>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td style="padding-bottom:15px;padding-top:5px;">
                        <?php echo trim(ucfirst($errorInfo->getTracking())); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </body>
</html>
